using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace GrpcNet.Generator
{
    internal static class Emitter
    {
        public const string BinderName = "Binder";
        public const string TagsName = "GrpcNetTags";

        private const string Protobuf = "global::GrpcNet.Protobuf.";
        private const string Core = "global::GrpcNet.";
        private const string Token = "global::System.Threading.CancellationToken";
        private const string Task = "global::System.Threading.Tasks.ValueTask";

        /// <summary>The fully qualified metadata name of the class a service is generated into.</summary>
        public static string ClassName(FileModel file, ServiceModel service)
            => file.Namespace.Length > 0 ? file.Namespace + "." + service.Name : service.Name;

        public static string HintName(FileModel file)
        {
            string name = file.ReflectionClass.StartsWith("global::", System.StringComparison.Ordinal) ? file.ReflectionClass.Substring(8) : file.ReflectionClass;
            return name + ".GrpcNet.g.cs";
        }

        public static string Emit(FileModel file)
        {
            var w = new Writer();
            w.Line("// <auto-generated/>");
            w.Line("// Generated by GrpcNet.Generator from " + file.ProtoFile + ". Do not edit.");
            w.Line("#nullable enable");
            w.Line();
            bool hasNamespace = file.Namespace.Length > 0;
            if (hasNamespace)
            {
                w.Line("namespace " + file.Namespace);
                w.Open();
            }

            bool first = true;
            foreach (ServiceModel service in file.Services)
            {
                if (!first)
                {
                    w.Line();
                }

                first = false;
                EmitService(w, file, service);
            }

            if (hasNamespace)
            {
                w.Close();
            }

            return w.ToString();
        }

        private static void EmitService(Writer w, FileModel file, ServiceModel service)
        {
            string self = "global::" + (file.Namespace.Length > 0 ? file.Namespace + "." : "") + Identifier(service.Name);
            w.Line("/// <summary>GrpcNet method objects and binder for the <c>" + service.FullName + "</c> service.</summary>");
            w.Line("[global::System.CodeDom.Compiler.GeneratedCode(\"GrpcNet.Generator\", \"1.0.0\")]");
            w.Line("public static partial class " + Identifier(service.Name));
            w.Open();
            foreach (MethodModel method in service.Methods)
            {
                string type = MethodType(method);
                w.Line("/// <summary>The " + KindText(method.Kind) + " method <c>/" + service.FullName + "/" + method.Name + "</c>.</summary>");
                w.Line("public static readonly " + Hide(method.Name) + type + " " + Identifier(method.Name) + " = " + type + ".Create<" + self + "." + TagsName + "." + Identifier(method.Name) + ">(" + file.ReflectionClass + ".Descriptor, \"" + service.FullName + "\", \"" + method.Name + "\");");
                w.Line();
            }

            // A value-type generic argument is never shared, so a tag of the method's own gives it its own compiled code.
            w.Line("/// <summary>One empty struct per method, so each method object's handlers run in code compiled for that method.</summary>");
            w.Line("private static class " + TagsName);
            w.Open();
            foreach (MethodModel method in service.Methods)
            {
                w.Line("public " + Hide(method.Name) + "struct " + Identifier(method.Name) + " { }");
            }

            w.Close();
            w.Line();

            w.Line("/// <summary>Binds a handler to every method of the service. Each handler is required, so leaving one out does not compile.</summary>");
            w.Line("public sealed class " + BinderName + " : " + Protobuf + "IServiceBinder");
            w.Open();
            foreach (MethodModel method in service.Methods)
            {
                w.Line(method.Kind == CallKind.Unary
                    ? "/// <summary>The handler for <c>" + method.Name + "</c>, made with <c>" + service.Name + "." + method.Name + ".Sync</c> or <c>.Async</c>.</summary>"
                    : "/// <summary>The handler for <c>" + method.Name + "</c>.</summary>");
                w.Line("public required " + Hide(method.Name) + HandlerType(method) + " " + Identifier(method.Name) + " { get; init; }");
                w.Line();
            }

            w.Line("void " + Protobuf + "IServiceBinder.BindTo(" + Core + "GrpcProcessorBuilder builder)");
            w.Open();
            w.Line(Protobuf + "GeneratedSupport.EnsureInitialized(typeof(" + self + "));");
            w.Line("global::Google.Protobuf.Reflection.ServiceDescriptor service = " + Protobuf + "GeneratedSupport.FindService(" + file.ReflectionClass + ".Descriptor, \"" + service.FullName + "\");");
            var methods = new StringBuilder();
            var handlers = new StringBuilder();
            var names = new StringBuilder();
            foreach (MethodModel method in service.Methods)
            {
                if (methods.Length > 0)
                {
                    methods.Append(", ");
                    handlers.Append(", ");
                    names.Append(", ");
                }

                methods.Append(self + "." + Identifier(method.Name));
                handlers.Append("this." + Identifier(method.Name));
                names.Append("\"" + method.Name + "\"");
            }

            w.Line(Protobuf + "GeneratedSupport.PreflightService(builder, service, new " + Protobuf + "GrpcMethod[] { " + methods + " }, new object?[] { " + handlers + " }, new string[] { " + names + " });");
            foreach (MethodModel method in service.Methods)
            {
                string bind = method.Kind == CallKind.Unary ? "GeneratedSupport.BindUnary" : "ProtobufBindings.Bind";
                w.Line(Protobuf + bind + "(builder, " + self + "." + Identifier(method.Name) + ", this." + Identifier(method.Name) + ");");
            }

            w.Line(Protobuf + "ProtobufBindings.AddService(builder, service, requireComplete: true);");
            w.Close();
            w.Close();
            w.Close();
        }

        private static string MethodType(MethodModel method)
        {
            string kind = method.Kind switch
            {
                CallKind.Unary => "UnaryMethod",
                CallKind.ServerStreaming => "ServerStreamingMethod",
                CallKind.ClientStreaming => "ClientStreamingMethod",
                _ => "DuplexMethod",
            };
            return Protobuf + kind + "<" + method.RequestType + ", " + method.ResponseType + ">";
        }

        private static string HandlerType(MethodModel method)
        {
            string request = method.RequestType;
            string response = method.ResponseType;
            return method.Kind switch
            {
                CallKind.Unary => Protobuf + "UnaryHandler<" + request + ", " + response + ">",
                CallKind.ServerStreaming => "global::System.Func<" + request + ", " + Core + "MessageWriter<" + response + ">, " + Token + ", " + Task + ">",
                CallKind.ClientStreaming => "global::System.Func<" + Core + "MessageReader<" + request + ">, " + Token + ", " + Task + "<" + response + ">>",
                _ => "global::System.Func<" + Core + "MessageReader<" + request + ">, " + Core + "MessageWriter<" + response + ">, " + Token + ", " + Task + ">",
            };
        }

        private static string KindText(CallKind kind) => kind switch
        {
            CallKind.Unary => "unary",
            CallKind.ServerStreaming => "server-streaming",
            CallKind.ClientStreaming => "client-streaming",
            _ => "bidirectional streaming",
        };

        private static string Identifier(string name)
            => SyntaxFacts.IsReservedKeyword(SyntaxFacts.GetKeywordKind(name)) ? "@" + name : name;

        // A member named like one of object's members hides it, which is a warning without "new".
        private static string Hide(string name) => name switch
        {
            "Equals" or "GetHashCode" or "GetType" or "ToString" or "ReferenceEquals" or "MemberwiseClone" => "new ",
            _ => "",
        };

        private sealed class Writer
        {
            private readonly StringBuilder _text = new StringBuilder();
            private int _indent;

            public void Line(string text = "")
            {
                if (text.Length > 0)
                {
                    _text.Append(' ', _indent * 4);
                    _text.Append(text);
                }

                _text.Append('\n');
            }

            public void Open()
            {
                Line("{");
                _indent++;
            }

            public void Close()
            {
                _indent--;
                Line("}");
            }

            public override string ToString() => _text.ToString();
        }
    }
}
